# fork Growthers/enshita
# https://github.com/Growthers/enshita/blob/main/.github/workflows/client-lint.yml
name: Lint backend

on:
  pull_request:
    branches:
      - master

env:
  workdir: backend
  node-version: lts/*

jobs:
  back-filter:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pull-requests: "read"
    outputs:
      backend: ${{steps.changes.outputs.backend}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{github.token}}
          filters: .github/filters.yml
  run-linter:
    runs-on: ubuntu-latest
    needs: back-filter
    if: needs.back-filter.outputs.backend == 'true'
    defaults:
      run:
        working-directory: ${{env.workdir}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.node-version}}
      - name: Install Dependencies
        run: yarn run lint --max-warnings=0
      - name: eslint
        run: yarn run lint --max-warnings=0
  run-linter-check:
    if: ${{! failure()}}
    needs: run-linter
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linter is successfully executed."
